import { Vehicle } from '../entity/vehicle.entity';

export const allVehiclesStub: Vehicle[] = [
  {
    id: 1,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Mazda',
    car_model: 'Axela',
    vin_number: '76767',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 3,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Audi',
    car_model: 'A6',
    vin_number: '756757',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 4,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Ford',
    car_model: 'Escape',
    vin_number: '224324',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 5,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Nissan',
    car_model: 'GT-R',
    vin_number: '65757',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 6,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Maruty',
    car_model: 'Axela',
    vin_number: '76767',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 7,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Toyota',
    car_model: 'Supra',
    vin_number: '435453',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 8,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Audi',
    car_model: 'A6',
    vin_number: '756757',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 9,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Ford',
    car_model: 'Escape',
    vin_number: '224324',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 10,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Nissan',
    car_model: 'GT-R',
    vin_number: '65757',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
  {
    id: 2,
    first_name: '',
    last_name: '',
    email: '',
    car_make: 'Toyota',
    car_model: 'Supra',
    vin_number: '435453',
    manufactured_date: '3/2/1985',
    age_of_vehicle: '',
  },
];
